language: node_js

cache:
  yarn: true

node_js:
- node
- lts/*

sudo: false
dist: xenial

matrix:
  fast_finish: true

notifications:
  email: false

before_deploy:
- yarn build

deploy:
  provider: npm
  email: leopard.not.a@gmail.com
  api_key:
    secure: aYduGwPC2fqITSzo3be5dAlP5p6H6PkYXOGCRXKUMn2F1jzjxkD5fwLtLJa7vLbAioV6/hWz/8GCLt5oVBrgtvvG4JKuR3PD4mBHfNyC/XDCTeYpql1M5lvbGQU4InGe8kIxxjpRSWrqSMoAWO/iZc7BA8TQ47ATGNLEY+b/pKTQbgQ7L32LdL4S0LV/ik+cRpfczlgSMv/yUErbA9onAgLeJQEz6dXZuBO7Yy9B208BBcQTVYvHNuaTu0uET6bfOaJzs0nICfpPKmfvJLwg9+XTiSIMCt6Gk/KnXxGfJ4w+2m3IYfsVbkMzenocNid/Ddw6zhSECrWZ/Bwh8yeR7Z79y+NVj9EGSKWoxNSaIhCBDr6sARcDGI3eP+nTieBR0qbu2/XCsWchz7vE2vjmQKIWRx8z0yh6O+Bkg+lQpO9c4yPuNCBP2jEyLDRiYop9xWTPaXuRXSLFTi7PpplKnrfA7TL6sG5//AWVPP3xHGlh4VfIPkg5PNV8/Lmfn8kv1HK6VSl+Q9vFcxrE9DFRPcaUsSmekrCqRUOFqIdEcOl5E0U848fzBZIh1soPR+mrKRWCAQSMKMFfq3DDJHuwiazvnuwsxQYK2Dc2guew6VfhT4jiU5vc4fh6e1Zpux8+eXlEvsdZPTJ88D8vIH/aEe6oH01+Iue0dmV2eGjEUhQ=
  on:
    tags: true
    repo: le0pard/storybook-addon-root-attribute
  skip_cleanup: true
